extends:
  airbnb-base

env:
  jest: true
  node: true
  es6: true

rules:
  max-len: [error, 120]
  semi: [error, never]
  comma-dangle: [error, always-multiline]
  quotes: [error, single]
  no-plusplus: off
  object-curly-spacing: [error, never]
  object-curly-newline: off
  no-param-reassign: off
  no-await-in-loop: off
  no-empty: [error, allowEmptyCatch: true]
  import/prefer-default-export: off
  no-nested-ternary: off
  linebreak-style: off
  global-require: off

settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src

globals:
  jest: true
  jasmine: true
  it: true
  xit: true
  expect: true
  jestExpect: true
  done: true
  describe: true
  beforeEach: true
  React: true
  Component: true
  PureComponent: true
  shallow: true
  render: true
  mount: true
  sinon: true
  localStorage: true
  fetch: true
  Promise: true
  sleep: true
  browser: true
