version: '2'
services:
    bc_wallet:
        build:
            context: ../stox-bc-wallet
            dockerfile: Dockerfile
        container_name: bc_wallet
        ports:
            - "3001:3001"
        tty: true
        environment:
            WEB_3_URL: 'http://10.250.2.207:8545/'
            DATABASE_URL: 'postgres://postgres:secret@bc_wallet_db/stox2'
            REQUIRED_CONFIRMATIONS: 12
            MAX_BLOCKS_READ: 10000
            NETWORK: 'MAIN'
        links:
            - bc_wallet_db
        depends_on:
            - bc_wallet_db

    bc_wallet_db:
        image: postgres
        container_name: bc_wallet_db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: postgres
            POSTGRES_DB: stox2
