version: '2'
services:
    db:
        image: postgres
        container_name: stox_db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: postgres
            POSTGRES_DB: stox2

    rabbitmq:
        image: rabbitmq:3-management
        container_name: stox_rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - hostname=rabbitmq