version: '3.3'
services:

    sut:
        image: wallet-manager
        container_name: ${SERVICE_NAME}-test
        depends_on:
            - activemq-wallet-test
            - wallet-manager-db-test
        env_file:
            - ../packages/${SERVICE_NAME}/.env.test
        environment:
            DATABASE_URL: postgres://postgres:secret@wallet-manager-db-test/stoxbcwallet
            MQ_CONNECTION_URL: stomp://activemq-wallet-test:61613
            SERVICE_NAME: $SERVICE_NAME
        networks:
            - subsystems
        tty: true
        entrypoint: npm run test --prefix packages/${SERVICE_NAME}

    wallet-manager-db-test:
        build:
            context: ../
            dockerfile: ./docker/db.Dockerfile
        container_name: stox-postgres-bc-wallet-test
        networks:
            - subsystems
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: postgres
            POSTGRES_DB: stoxbcwallet

    activemq-wallet-test:
        image: rmohr/activemq:5.14.5
        container_name: activemq-wallet-test
        networks:
            - subsystems

networks:
    subsystems:
        driver: bridge
