version: '3.3'
services:

    wallet-manager-db:
        build:
            context: ../
            dockerfile: ./docker/db.Dockerfile
        container_name: stox-postgres-bc-wallet
        ports:
            - 5433:5432
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: postgres
            POSTGRES_DB: stoxbcwallet

    activemq:
        image: rmohr/activemq:5.14.5
        container_name: stox-activemq
        ports:
            - 61613:61613
            - 8161:8161
