version: '3.3'
services:

    sut:
        image: $IMAGE_NAME
        container_name: sut
        depends_on:
            - wallet-manager-db-test
        environment:
            DATABASE_URL: postgres://postgres:secret@wallet-manager-db-test/stoxbcwallet
        networks:
            - subsystems
        tty: true
        entrypoint: bash -c "lerna run test:integration"
        volumes:
          - ../packages:/services/packages

    wallet-manager-db-test:
        build:
            context: ../
            dockerfile: ./docker/db.Dockerfile
        container_name: stox-postgres-bc-wallet-test
        networks:
            - subsystems
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: postgres
            POSTGRES_DB: stoxbcwallet

networks:
    subsystems:
        driver: bridge
